name: Deploy Dumi to GitHub Pages

on:
  push:
    branches:
      - main # 触发部署的分支，根据需要修改

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # 根据你的项目需求选择版本
          package-manager: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build project
        run: npm run docs:build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs-dist # 默认构建输出目录
